/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universidadbeta_escritorio;

/**
 *
 * @author contr
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonVerDonadores = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        botonVerDonativos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        verPagos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        verEventos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        verRepresentantes = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        verReportes = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setText("Menu Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\contr\\Downloads\\handshake.png")); // NOI18N
        jLabel2.setText("Donadores");

        botonVerDonadores.setBackground(new java.awt.Color(255, 204, 204));
        botonVerDonadores.setIcon(new javax.swing.ImageIcon("C:\\Users\\contr\\Downloads\\arrow-up-right.png")); // NOI18N
        botonVerDonadores.setText("Entrar");
        botonVerDonadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerDonadoresActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\contr\\Downloads\\coins.png")); // NOI18N
        jLabel3.setText("Donativos");

        botonVerDonativos.setBackground(new java.awt.Color(0, 204, 204));
        botonVerDonativos.setIcon(new javax.swing.ImageIcon("C:\\Users\\contr\\Downloads\\arrow-up-right.png")); // NOI18N
        botonVerDonativos.setText("Entrar");
        botonVerDonativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerDonativosActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\contr\\Downloads\\calendar-clock.png")); // NOI18N
        jLabel4.setText("Pagos");

        verPagos.setBackground(new java.awt.Color(255, 51, 0));
        verPagos.setIcon(new javax.swing.ImageIcon("C:\\Users\\contr\\Downloads\\arrow-up-right.png")); // NOI18N
        verPagos.setText("Entrar");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\contr\\Downloads\\calendar-lines-pen.png")); // NOI18N
        jLabel5.setText("Eventos");

        verEventos.setBackground(new java.awt.Color(255, 0, 51));
        verEventos.setIcon(new javax.swing.ImageIcon("C:\\Users\\contr\\Downloads\\arrow-up-right.png")); // NOI18N
        verEventos.setText("Entrar");
        verEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEventosActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\contr\\Downloads\\people-poll.png")); // NOI18N
        jLabel6.setText("Representantes");

        verRepresentantes.setBackground(new java.awt.Color(255, 0, 51));
        verRepresentantes.setIcon(new javax.swing.ImageIcon("C:\\Users\\contr\\Downloads\\arrow-up-right.png")); // NOI18N
        verRepresentantes.setText("Entrar");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\contr\\Downloads\\file-invoice.png")); // NOI18N
        jLabel7.setText("Reportes");

        verReportes.setBackground(new java.awt.Color(255, 0, 0));
        verReportes.setIcon(new javax.swing.ImageIcon("C:\\Users\\contr\\Downloads\\arrow-up-right.png")); // NOI18N
        verReportes.setText("Entrar");

        botonCerrarSesion.setBackground(new java.awt.Color(255, 153, 0));
        botonCerrarSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\contr\\Downloads\\exit.png")); // NOI18N
        botonCerrarSesion.setText("Cerrar Sesion ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(verEventos)
                    .addComponent(botonVerDonadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonVerDonativos)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(verRepresentantes))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verPagos)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(verReportes))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(botonCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVerDonadores)
                    .addComponent(botonVerDonativos)
                    .addComponent(verPagos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verEventos)
                    .addComponent(verRepresentantes)
                    .addComponent(verReportes))
                .addGap(43, 43, 43)
                .addComponent(botonCerrarSesion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerDonadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerDonadoresActionPerformed
        Donadores ventana = new Donadores();
    ventana.setVisible(true);
    }//GEN-LAST:event_botonVerDonadoresActionPerformed

    private void verEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEventosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verEventosActionPerformed

    private void botonVerDonativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerDonativosActionPerformed
         Donativos ventana = new Donativos();
    ventana.setVisible(true);
    }//GEN-LAST:event_botonVerDonativosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonVerDonadores;
    private javax.swing.JButton botonVerDonativos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton verEventos;
    private javax.swing.JButton verPagos;
    private javax.swing.JButton verReportes;
    private javax.swing.JButton verRepresentantes;
    // End of variables declaration//GEN-END:variables
}
